[tool]
[tool.poetry]
name = "BrendUserBot_Deployer"
version = "3.0"
description = "Automatic Deploy BrendUserBot to Heroku"
authors = ["Hüsü <@BrendOwner>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
